In [1]:
import pandas as pd

df = pd.read_csv('./data/train.csv')
df

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  \
0       100000          s       138.470                       51.655   
1       100001          b       160.937                       68.768   
2       100002          b      -999.000                      162.172   
3       100003          b       143.905                       81.417   
4       100004          b       175.864                       16.915   
...        ...        ...           ...                          ...   
249995  349995          b      -999.000                       71.989   
249996  349996          b      -999.000                       58.179   
249997  349997          s       105.457                       60.526   
249998  349998          b        94.951                       19.362   
249999  349999          b      -999.000                       72.756   

        DER_mass_vis  DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  \
0             97.827    27.980                  0.91           124.711   
1            103.235    48.146               -999.00          -999.000   
2            125.953    35.635               -999.00          -999.000   
3             80.943     0.414               -999.00          -999.000   
4            134.805    16.405               -999.00          -999.000   
...              ...       ...                   ...               ...   
249995        36.548     5.042               -999.00          -999.000   
249996        68.083    22.439               -999.00          -999.000   
249997        75.839    39.757               -999.00          -999.000   
249998        68.812    13.504               -999.00          -999.000   
249999        70.831     7.479               -999.00          -999.000   

        DER_prodeta_jet_jet  DER_deltar_tau_lep  ...  PRI_met_phi  \
0                     2.666               3.064  ...       -0.277   
1                  -999.000               3.473  ...       -1.916   
2                  -999.000               3.148  ...       -2.186   
3                  -999.000               3.310  ...        0.060   
4                  -999.000               3.891  ...       -0.871   
...                     ...                 ...  ...          ...   
249995             -999.000               1.392  ...        2.859   
249996             -999.000               2.585  ...       -0.867   
249997             -999.000               2.390  ...       -2.890   
249998             -999.000               3.365  ...        0.811   
249999             -999.000               2.025  ...       -1.596   

        PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0             258.733            2              67.435                2.150   
1             164.546            1              46.226                0.725   
2             260.414            1              44.251                2.053   
3              86.062            0            -999.000             -999.000   
4              53.131            0            -999.000             -999.000   
...               ...          ...                 ...                  ...   
249995        144.665            0            -999.000             -999.000   
249996         80.408            0            -999.000             -999.000   
249997        198.907            1              41.992                1.800   
249998        112.718            0            -999.000             -999.000   
249999         99.405            0            -999.000             -999.000   

        PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0                     0.444                 46.062                    1.24   
1                     1.158               -999.000                 -999.00   
2                    -2.028               -999.000                 -999.00   
3                  -999.000               -999.000                 -999.00   
4                  -999.000               -999.000                 -999.00   
...         

In [2]:
pd.get_option("display.max_columns")

20

In [3]:
for column in df:
    print(column, (df[column]==-999).sum())

Id 0
Prediction 0
DER_mass_MMC 38114
DER_mass_transverse_met_lep 0
DER_mass_vis 0
DER_pt_h 0
DER_deltaeta_jet_jet 177457
DER_mass_jet_jet 177457
DER_prodeta_jet_jet 177457
DER_deltar_tau_lep 0
DER_pt_tot 0
DER_sum_pt 0
DER_pt_ratio_lep_tau 0
DER_met_phi_centrality 0
DER_lep_eta_centrality 177457
PRI_tau_pt 0
PRI_tau_eta 0
PRI_tau_phi 0
PRI_lep_pt 0
PRI_lep_eta 0
PRI_lep_phi 0
PRI_met 0
PRI_met_phi 0
PRI_met_sumet 0
PRI_jet_num 0
PRI_jet_leading_pt 99913
PRI_jet_leading_eta 99913
PRI_jet_leading_phi 99913
PRI_jet_subleading_pt 177457
PRI_jet_subleading_eta 177457
PRI_jet_subleading_phi 177457
PRI_jet_all_pt 0


In [4]:
print((df['Prediction']=='s').sum())

85667


In [5]:
df.PRI_jet_num.value_counts()

0    99913
1    77544
2    50379
3    22164
Name: PRI_jet_num, dtype: int64

In [6]:
from helpers import *
PATH = './data/train.csv'
y_raw, tx_raw, ids_raw = load_csv_data(PATH)
print(y_raw, tx_raw, ids_raw)

[ 1. -1. -1. ...  1. -1. -1.] [[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]] [100000 100001 100002 ... 349997 349998 349999]


In [7]:
print(y_raw.shape)
print(tx_raw.shape)

(250000,)
(250000, 30)


In [8]:
lambda_max = np.linalg.eigvals(tx_raw.T @ tx_raw).max()
lambda_min = np.linalg.eigvals(tx_raw.T @ tx_raw).min()
print(lambda_max, lambda_min, lambda_max/lambda_min)

1433657413944.2444 0.018716709833493845 76597726133398.3


In [9]:
y_raw[y_raw==-1] = 0
y_raw = y_raw.reshape(-1, 1)
y = y_raw

In [10]:
col_mask = np.zeros(tx_raw.shape[1], dtype=bool)
col_mask[[1, 2, 3, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]] = True
tx_cleaned = tx_raw[:, col_mask]
tx_cleaned.shape

(250000, 18)

In [11]:
lambda_max = np.linalg.eigvals(tx_cleaned.T @ tx_cleaned).max()
lambda_min = np.linalg.eigvals(tx_cleaned.T @ tx_cleaned).min()
print(lambda_max, lambda_min, lambda_max/lambda_min)

28883717934.663532 30427.822613370296 949253.526999718


In [33]:
from implementations import *


def predict_linear(tx, w, threshold=0.5):
    """Predict values from linear regression. If probability > threshold, predict 1.
    Args:
        tx: numpy array of shape (N, D), D is the number of features.
        w: optimal weights, numpy array of shape(D, 1), D is the number of features.
        threshold: scalar, default = 0.5, threshold for decision.

    Returns:    
        y_pred: numpy array of shape (N, 1) with labels 1 or 0, N is the number of samples.
    """

    y_pred = tx @ w
    y_pred[y_pred>=threshold] = 1
    y_pred[y_pred<threshold] = 0
    
    return y_pred


def predict_logistic(tx, w, threshold=0.5):
    """Predict values from logistic regression. If probability > threshold, predict 1.
    Args:
        tx: numpy array of shape (N, D), D is the number of features.
        w: optimal weights, numpy array of shape(D, 1), D is the number of features.
        threshold: scalar, default = 0.5, threshold for decision.

    Returns:    
        y_pred: numpy array of shape (N, 1) with labels 1 or 0, N is the number of samples.
    """

    y_pred = sigmoid(tx @ w)
    y_pred[y_pred>=threshold] = 1
    y_pred[y_pred<threshold] = 0

    return y_pred


def compute_metrics(y, y_pred):
    """Compute prediction accuracy, f1-score, precision, recall.
    Args:
        y: numpy array of shape (N, 1), the true label.
        y_pred: numpy array of shape (N, 0), the prediction.

    Returns:    
        accuracy: the scalar of accuracy.
        f1_score: the scalar of f1_score.
        precision: the scalar of precision.
        recall: the scalar of recall.
    """

    accuracy = (y==y_pred).sum() / y.shape[0]
    precision = ((y==y_pred) & (y==1)).sum() / y_pred.sum()
    recall = ((y==y_pred) & (y==1)).sum() / y.sum()
    f1_score = 2 / (1 / precision + 1 / recall)
    return accuracy, precision, recall, f1_score

In [13]:
def standardization(tx):
    """Standardize the input by (X-mu) / sigma
    Args:
        tx: numpy array of shape (N, D), D is the number of features.

    Returns:    
        tx_std: standardized numpy array of shape (N, D), D is the number of features.
    """

    eps = 1e-9  # avoid being divided by zero
    return (tx - np.mean(tx, axis=0)) / (eps + np.std(tx, axis=0))

In [14]:
GAMMA = 0.1
LAMBDA = 1e-4
MAX_ITER = 500
THRESHOLD = 85667 / 250000

In [17]:
tx = standardization(tx_cleaned)
y = y_raw
initial_w = np.random.rand(tx.shape[1], 1)

In [30]:
w, loss = reg_logistic_regression(y, tx, LAMBDA, initial_w, 1000, 0.1)
print(w, loss)

[[-0.55618927]
 [-0.65038192]
 [ 0.20074515]
 [ 0.71353526]
 [-0.11200572]
 [ 0.0134177 ]
 [-0.29225823]
 [ 0.26761574]
 [ 0.64496985]
 [-0.00269806]
 [-0.00235093]
 [ 0.5052198 ]
 [-0.00127326]
 [ 0.00562096]
 [ 0.15065624]
 [ 0.00164643]
 [-0.22893156]
 [ 0.08631073]] 0.5837006323020231


In [34]:
y_pred = predict_logistic(tx, w)
accuracy, precision, recall, f1_score = compute_metrics(y, y_pred)
print(accuracy, precision, recall, f1_score)

0.707288 0.5485745400801213 0.8232108046272193 0.6584010979264501


In [36]:
w, loss = ridge_regression(y, tx, LAMBDA)
y_pred = predict_linear(tx, w)
accuracy, precision, recall, f1_score = compute_metrics(y, y_pred)
print(accuracy, precision, recall, f1_score)

0.657412 0.6 0.0007003863798195338 0.0013991395291895483


正类数量少, recall 低说明实际的正类没有多少被预测到, model 没怎么预测正类, 大部分全部预测负类.

TODO:

- adaptive learning rate and adam
- 针对不同的 pri_jet_num 分别学习不同的模型
- polynomial